### ISSUE TITLE
[Bug] Can't run `npm start` on Windows

### ISSUE THREAD

**Issue by kafiln** [smakosh/CRA-boilerplate#1]
I can't run `npm start` on windows 👇

![Capture](https://user-images.githubusercontent.com/15774583/84334604-aaf15280-ab8a-11ea-97b3-563a675c4481.PNG)

**Comment by JefferyHus** [comment]
open a PR, remove `PORT` from command line and add it directly to `.env` or use `cross-env` package

**Comment by kafiln** [comment]
I added cross-env and made a PR  #2
