### ISSUE TITLE
chore: ⚒️ no need to specify PORT in react-scripts start

### ISSUE THREAD

**Issue by chihab** [smakosh/CRA-boilerplate#12]
Hey @smakosh just saw your boilerplate 👍

It is probably better let the user put its conf in a .env file as documented here https://create-react-app.dev/docs/advanced-configuration rather than inlining it in npm scripts, that would work cross platform (via dotenv).

That way no need to have the "cross-env" dependency.

**Comment by smakosh** [comment]
True! I'll work on that, thank you!
