### ISSUE TITLE
Typescript version

### ISSUE THREAD

**Issue by fdrissi** [smakosh/CRA-boilerplate#9]
Hey @smakosh 👋 ,
I have a suggestion: a typescript version of your boilerplate.
it will be on another branch, so anyone can use the js or ts version.
what do you think?

**Comment by smakosh** [comment]
Yes I was planning to do it, feel free to kick start it & I'll contribute when I can! Great suggestion!

Thank you

**Comment by fdrissi** [comment]
✔️ 
thank you.

**Comment by smakosh** [comment]
Added here: https://github.com/smakosh/CRA-boilerplate/tree/typescript
